# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.IntegerField(max_length=10000),
        ),
    ]
